import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Container, Col } from "@nextui-org/react";
import Landing from "../src/flat/Landing";
import styles from "../styles/Home.module.css";
import { url } from "inspector";
import blurr from "../public/blurrBGfilled.png"

const Home: NextPage = () => {
  return (
    <div
      className={styles.container}
      style={{
        backgroundImage: "url('/blurrBG.png')",
        backgroundSize: "cover ",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Landing />
      </Container>
    </div>
  );
};

export default Home;
